name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "---- Setting AWS environment ----"
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/ppe_model
            if [ ! -d ~/ppe_model ]; then
              git clone https://github.com/uctconsulting12/ppe_model.git ~/ppe_model
            else
              cd ~/ppe_model
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/ppe_model
            sudo docker build -t ppe_image .

            echo "---- Stopping old container ----"
            sudo docker stop ppe_container || true
            sudo docker rm ppe_container || true

            echo "---- Running new container with AWS creds ----"
            sudo docker run -d \
            --name ppe_container \
            -p 8000:8000 \
            --gpus all
            -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
            ppe_image

            echo "Deployment completed. "
